// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqZ9LdtukUe3alNLDbFTOyTDnzTg-H1Co',
    appId: '1:945939958431:web:244af48d925fee33aaf0aa',
    messagingSenderId: '945939958431',
    projectId: 'tender-a6b09',
    authDomain: 'tender-a6b09.firebaseapp.com',
    storageBucket: 'tender-a6b09.appspot.com',
    measurementId: 'G-NX2S560Z40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHg6pQXd0Ah_76DAlMduHc7L_LWxi1hM4',
    appId: '1:945939958431:android:a208ac13e660b8feaaf0aa',
    messagingSenderId: '945939958431',
    projectId: 'tender-a6b09',
    storageBucket: 'tender-a6b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzjudFP6xkQ3jR_eS6mpg01EgI6lkMEY',
    appId: '1:945939958431:ios:8b3babaa4916fa26aaf0aa',
    messagingSenderId: '945939958431',
    projectId: 'tender-a6b09',
    storageBucket: 'tender-a6b09.appspot.com',
    androidClientId: '945939958431-q33620u69f34m4a611fqqe67lfe5uc8l.apps.googleusercontent.com',
    iosClientId: '945939958431-7co6o96emqgt4tuhcf15ckhbi3oig7pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDzjudFP6xkQ3jR_eS6mpg01EgI6lkMEY',
    appId: '1:945939958431:ios:8b3babaa4916fa26aaf0aa',
    messagingSenderId: '945939958431',
    projectId: 'tender-a6b09',
    storageBucket: 'tender-a6b09.appspot.com',
    androidClientId: '945939958431-q33620u69f34m4a611fqqe67lfe5uc8l.apps.googleusercontent.com',
    iosClientId: '945939958431-7co6o96emqgt4tuhcf15ckhbi3oig7pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vender',
  );
}
